

[controls]
knob1 = [] # param keys that will be bound to knob 1
knob2 = [] # param keys that will be bound to knob 2

# set knobs up to 16 !

# Example
# [controls]
# knob1 = ["mix"]
# knob2 = ["output_gain", "decay_time"]
#

################################################################################
# ______ _____ _____ _    _ _____ _____
# | ___ \_   _|_   _| |  | |_   _|  __ \
# | |_/ / | |   | | | |  | | | | | |  \/
# | ___ \ | |   | | | |/\| | | | | | __
# | |_/ /_| |_  | | \  /\  /_| |_| |_\ \
# \____/ \___/  \_/  \/  \/ \___/ \____/
#
################################################################################
# Examples
#
# [[bitwig]]
# id = "72a3018d-788b-472c-b1d7-16419d00f4c6"
# params.mix = "MIX"
#
# [[bitwig]]
# id = "b5b2b08e-730e-4192-be71-f572ceb5069b"
# params.mix = "MIX"
# params.output_gain = "LEVEL"

################################################################################
#  _   _ _____ _____ _____
# | | | /  ___|_   _|____ |
# | | | \ `--.  | |     / /
# | | | |`--. \ | |     \ \
# \ \_/ /\__/ / | | .___/ /
#  \___/\____/  \_/ \____/
#
################################################################################
# Example
#
# [[vst3]]
# id = "5653547665653376616C68616C6C6176"
# params.mix = 48
# params.decay_time = 50

################################################################################
#  _   _ _____ _____ _____
# | | | /  ___|_   _/ __  \
# | | | \ `--.  | | `' / /'
# | | | |`--. \ | |   / /
# \ \_/ /\__/ / | | ./ /___
#  \___/\____/  \_/ \_____/
#
################################################################################
# Example
#
# [[vst2]]
# id = 1315513406
# params.mix = 11
